language: php

php:
  - 7.0

branches:
  only:
    - master
    - development
    - /^feature\/.+$/

before_script:
 - git checkout $TRAVIS_BRANCH
 - curl -sS 'https://getcomposer.org/installer' | php -- --install-dir=/usr/local/bin --filename=composer
 - chmod +x /usr/local/bin/composer
 - /usr/local/bin/composer install -o --prefer-dist --no-interaction
 - mkdir build/logs

script:
 - php build/tools/phpunit.phar -c build/

after_script:
 - php build/tools/coveralls.phar -c ./.coveralls.yml -v --exclude-no-stmt
