language: php

php:
  - 7.0

branches:
  only:
    - master
    - development
    - /^feature\/.+$/

before_script:
 - git checkout $TRAVIS_BRANCH
 - composer self-update
 - composer install -o --prefer-dist --no-interaction
 - mkdir build/logs

script:
 - php build/tools/phpunit.phar -c build/

after_script:
 - php build/tools/coveralls.phar -c ./.coveralls.yml -v --exclude-no-stmt
